* require
 - sbcl >= 1.4
 - asdf >= 3.0
** reccommendation
   - quicklisp (Plaease update with ~(ql:update-client)~)
* usage
** shape movie_lines.txt

   #+BEGIN_SRC shell
$ cd ~/common-lisp
~/common-lisp $ git clone [this repository]

   < download Cornell Movie-Dialogs Corpus's zip file and unzip it >
   < link https://www.cs.cornell.edu/~cristian/Cornell_Movie-Dialogs_Corpus.html>
  
~/common-lisp $ sbcl
   
> (asdf:load-system :corpas)
> (in-package :parse)
> (shape-movie-lines "/path/to/unzipped-folder/movie_lines.txt")


"EOF"
> (SB-EXT:EXIT)

~/common-lisp $ cd /path/to/unzipped-folder

/path/to/unzipped-folder $ wc -l movie_lines_shaped.txt

304713 movie_lines_shaped.txt

/path/to/unzipped-folder $ head -n 3 movie_lines_shaped.txt

L1045|they do not !
L1044|they do to !
L985|i hope so .

#+END_SRC

** shape movie_conversations.txt

   #+BEGIN_SRC shell
~/common-lisp $ sbcl
   
> (asdf:load-system :corpas)
> (in-package :parse)
> (shape-movie-conversations "/path/to/unzipped-folder/movie_conversations.txt")


"EOF"
> (SB-EXT:EXIT)

~/common-lisp $ cd /path/to/unzipped-folder
/path/to/unzipped-folder $ head -n 3 movie_conversations_shaped.txt 
L194|L195|L196|L197
L198|L199
L200|L201|L202|L203
#+END_SRC

** create dictionary

   #+BEGIN_SRC shell
~/common-lisp $ sbcl
   
> (asdf:load-system :corpas)
> (in-package :dict)
> (create-dictionary "/path/to/unzipped-folder/movie_lines_shaped.txt")

"EOF"
> (SB-EXT:EXIT)

~/common-lisp $ cd /path/to/unzipped-folder
/path/to/unzipped-folder $ head -n 3 movie_dictionary.txt 
they
do
not
#+END_SRC

* What's next?
 Try Flare [clojure] or MGL [common lisp] for Seq2Seq or some deep learning methods.
 
** tips
   In Archlinux, before install MGL, you should install cuda, and add below code in your =~/,bashrc=
   #+BEGIN_SRC shell
   export C_INCLUDE_PATH=/opt/cuda/include:$C_INCLUDE_PATH
   export LD_LIBRARY_PATH=/opt/cuda/lib64:${LD_LIBRARY_PATH}
   #+END_SRC
* Licence
 MIT licence

Copyright 2018 Meguru Mokke

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
